#use case 1

LLM_PROVIDER = "XXXXXXXX"
TEMPERATURE = "XXXXXXXX"
MAX_TOKENS = "XXXXXXXX"
TOP_P = "XXXXXXXX"
AZURE_OPENAI_DEPLOYMENT_NAME = "XXXXXXXX"
AZURE_OPENAI_API_KEY = "XXXXXXXX"
AZURE_OPENAI_ENDPOINT = "XXXXXXXX"
AZURE_OPENAI_API_VERSION = "XXXXXXXX"
EMBEDDING_MODEL = "XXXXXXXX"
GOOGLE_APPLICATION_CREDENTIALS = "XXXXXXXX"
GCP_PROJECT_ID = "XXXXXXXX"
BIGQUERY_DATASET = "XXXXXXXX"
BIGQUERY_TABLE = "XXXXXXXX"
VISUALIZATIONS = "XXXXXXXX"
CHATBOT_NAME = "XXXXXXXX"
CHATBOT_DESCRIPTION = "XXXXXXXX"

#usecase 2

# =======================
# Default Provider
# =======================
LLM_PROVIDER = "XXXXXXXX"

# =======================
# Model Parameters
# =======================
TEMPERATURE = "XXXXXXXX"
MAX_TOKENS = "XXXXXXXX"
TOP_P = "XXXXXXXX"

# =======================
# Azure OpenAI Settings
# =======================
AZURE_OPENAI_DEPLOYMENT_NAME = "XXXXXXXX"
AZURE_OPENAI_API_KEY = "XXXXXXXX"
AZURE_OPENAI_ENDPOINT = "XXXXXXXX"
AZURE_OPENAI_API_VERSION = "XXXXXXXX"

# =======================
# Google Gemini Settings
# =======================
GOOGLE_API_KEY = "XXXXXXXX"
GEMINI_LLM_1 = "XXXXXXXX"
GEMINI_LLM_2 = "XXXXXXXX"

# =======================
# Embedding Models
# =======================
AZURE_EMBEDDING_MODEL = "XXXXXXXX"
GOOGLE_EMBEDDING_MODEL = "XXXXXXXX"
